// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingMusicData;

#nullable disable

namespace WeddingMusicData.Migrations
{
    [DbContext(typeof(WeddingMusicContext))]
    [Migration("20240104000000_AddPlaylistChainAndLoop")]
    partial class AddPlaylistChainAndLoop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WeddingMusicData.Models.CueSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadeInCurve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadeInMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadeOutCurve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadeOutMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GainTrimDb")
                        .HasColumnType("REAL");

                    b.Property<long?>("MixInPointMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MixOutPointMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StopMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("CueSettings");
                });

            modelBuilder.Entity("WeddingMusicData.Models.PlaylistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransitionModeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistSectionId", "Position");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("WeddingMusicData.Models.PlaylistSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCrossfadeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLooping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextSectionId");

                    b.HasIndex("Order");

                    b.ToTable("PlaylistSections");
                });

            modelBuilder.Entity("WeddingMusicData.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<string>("CachedFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CachedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Danceability")
                        .HasColumnType("REAL");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalUri")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCachedOffline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastIngestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LoudnessLufs")
                        .HasColumnType("REAL");

                    b.Property<string>("Mood")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicalKey")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Bpm");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("Genre");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("IsCachedOffline");

                    b.HasIndex("Title");

                    b.HasIndex("Artist", "Title");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("WeddingMusicData.Models.CueSettings", b =>
                {
                    b.HasOne("WeddingMusicData.Models.Track", "Track")
                        .WithOne("CueSettings")
                        .HasForeignKey("WeddingMusicData.Models.CueSettings", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("WeddingMusicData.Models.PlaylistItem", b =>
                {
                    b.HasOne("WeddingMusicData.Models.PlaylistSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingMusicData.Models.Track", "Track")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("WeddingMusicData.Models.PlaylistSection", b =>
                {
                    b.HasOne("WeddingMusicData.Models.PlaylistSection", "NextSection")
                        .WithMany()
                        .HasForeignKey("NextSectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Items");

                    b.Navigation("NextSection");
                });

            modelBuilder.Entity("WeddingMusicData.Models.Track", b =>
                {
                    b.Navigation("CueSettings");

                    b.Navigation("PlaylistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
